# Introduction to NumPy

NumPy (numerical Python) is a library that consists of multidimensional array objects and a set of routines for processing them. NumPy allows you to perform mathematical and logical operations on arrays. This tutorial walks you through the fundamentals of NumPy, including its design and architectue. It also covers array features, indexing types, and other topics.

## Numpy Installation

In [1]:
!pip install numpy

## Import NumPy

In [2]:
import numpy

### NumPy is usually imported under the np alias.

In [3]:
import numpy as np

## Check Python and Numpy Version


In [4]:
import platform
import numpy as np
print('Python version: ' + platform.python_version())
print('Numpy version: ' + np.__version__)

Python version: 3.7.6
Numpy version: 1.19.5


# Create a NumPy Array

## Create an 1D Array


In [5]:
# Creating a 1-D array using a list
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
# Creating a 1-D array using a tuple
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [8]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## Create an 2D Array with Specified Data Type

In [9]:
arr = np.array([[1,2,3], [4,5,6]], dtype='int')
print(arr)
print('Data Type:',arr.dtype)

[[1 2 3]
 [4 5 6]]
Data Type: int32


## Create an 3D Array

In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Create an aray within specified range

np.arange() method can be used to replace np.array(range()) method

In [11]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


## Create an array of evenly spaced numbers within specified range

In [12]:
arr, step_size = np.linspace(0, 5, 8, endpoint=False, retstep=True)
print(arr)
print('The step size is ' + str(step_size))

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
The step size is 0.625


## Create an array of random values of given shape

np.random.rand() method returns values in the range [0,1)

In [13]:
np.random.rand()

0.24055090398731804